version: '3'

services:
  wyb:
    image: ztl8702/wyb:latest
    ports: 
      - '80:3000'
    restart: always
    environment:
      WYB_ENVIRONMENT: production
      WYB_DB: postgres://postgres:password@db:5432/wyb  # change this
    link:
      - pg:db
    depends_on:
      - pg
  
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example # change this
      POSTGRES_DB: wyb
    volumes:
      - ./data:/var/lib/postgresql/data # change this
    expose:
      - '5555:5432'
  